server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 是否把自己当前eurekaServer模块也注册到 注册中心去
    fetch-registry: false #是否同步其他的Eureka Server注册中心的数据
    service-url:
      defaultZone: http://localhost:8761/eureka #默认的注册中心访问地址路径
