server:
  port: 8050
spring:
  application:
    name: feign #当前服务注册在Eureka Server上的名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #微服务注册访问的注册中心地址
  instance:
    prefer-ip-address: true #是否将当前服务的ip注册到Eureka Server
feign:
  hystrix:
    enabled: true #启用hystrix熔断机制